spring:
  profiles:
    active:
      - local
--- # default 설정
spring:
  profiles:
    group:
      local:
        - redis-local
        - security-local
        - db-local
      dev:
        - redis-dev
        - security-dev
        - db-dev
    include:
      - security
      - redis
      - db
  config:
    import: application-oauth.yml, application-storage.yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    org.springframework.cache: INFO
server:
  tomcat:
    connection-timeout: 180000
--- # local 설정
spring:
  config:
    activate:
      on-profile: local
server:
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: bns-ssl
  port: 80
logging:
  level:
    root : DEBUG
--- # dev 설정
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080

