spring:
  profiles:
    active:
      - local
    group:
      local:
        - redis-local
        - security-local
      dev:
        - redis-dev
        - security-dev
    include:
      - db
      - security
      - redis
  config:
    import: application-oauth.yml, application-storage.yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: bns-ssl
  port: 80



