spring:
  profiles:
    active:
      - dev
    group:
      local:
        - redis-local
        - security-local
        - db-local
      dev:
        - redis-dev
        - security-dev
        - db-dev
    include:
      - security
      - redis
      - db
  config:
    import: application-oauth.yml, application-storage.yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080

logging:
  level:
    org.springframework.cache: DEBUG