spring:
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
  profiles:
    include: db
  config:
    import: application-oauth.yml, application-security.yml
server:
  port: 80
