spring:
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
  profiles:
    include: db
  config:
    import: application-oauth.yml, application-security.yml
server:
#  ssl:
#    enabled: true
#    key-store: keystore.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: bns-ssl
  port: 80

cloud:
  aws:
    s3:
      bucket: <S3 버킷 이름>
    credentials:
      access-key: <저장해놓은 액세스 키>
      secret-key: <저장해놓은 비밀 액세스 키>
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


