spring:
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
  profiles:
    include: db
  config:
    import: application-oauth.yml, application-security.yml, application-oauth.yml, application-storage.yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: localhost
    port: 6379
server:
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: bns-ssl
  port: 80



